### ISSUE TITLE
Public docker image

### ISSUE THREAD

**Issue by cjyar** [xmatters/cthulhu-chaos-testing#7]
It seems like many common use cases don't require a custom docker image; config files can just be injected into the container. Could you make a public image available?

**Comment by gabie-giraffe** [comment]
Hi Chris,

That is a great suggestion! We have an image that we use internally and we do inject the configs and scenario files to it.

I am planning to clean it up and add it to the repository.

Thanks,

**Comment by gabie-giraffe** [comment]
Hi Chris,

Thanks to @curtisstpierre, we now have an public image on Docker Hub: https://hub.docker.com/r/xmattersinc/cthulhu
