### ISSUE TITLE
Improve instructions to setup the K8s engine

### ISSUE THREAD

**Issue by gabie-giraffe** [xmatters/cthulhu-chaos-testing#8]
The readme instruction to setup the K8s engine is not clear enough regarding its default value.

> This is generally ~/.kube/config for the current user.
Sounds like one needs to setup Cthulhu to a kube config locataion where this is in fact the default.

**Comment by sathiyajith** [comment]
Can you please explain me how to setup cthulhu on k8s cluster and integrate with slack?

**Comment by gundal** [comment]
> Can you please explain me how to setup cthulhu on k8s cluster and integrate with slack?

Hey sathiyaijith. Could you elaborate a little on what you are having trouble with? Do you need a command line example for running the container or is it the slack portion that is giving you an issue.

If you need help with the slack portion, you need to create a simple slack app, and select incoming webhooks which will get you a webhook url that you can pass into Cthulhu and get notifications there. 

Here is a great guide to do that: https://api.slack.com/messaging/webhooks

If you are having troubles just getting started with k8s perhaps this example will help:

1. `docker pull xmattersinc/cthulhu`

```
2. 
docker create --name cthulhu \ 
-v "/[Filepath of gcp service account/key].json:/etc/secrets/gcp-account.json" \
-v "/Users/[mac user id]/.kube/config:/etc/secrets/kube.config" \ 
-v "/[Filepath to clone of cthulhu]/scenarioFiles/[YourSceario].yaml:/etc/cthulhu/scenario.yaml" \
-e GCP_PROJECT=[Your GCP Project Name] \
-e SLACK_WEBHOOK_URL=https://hooks.slack.com/services/[XX#XX###]/[X#X#X#X##X]/[XXXXXX#####] \ xmattersinc/cthulhu
```


3. `docker start cthulhu`

4. To see the log outputs use 
`docker attach cthulhu`
